[tool.poetry]
name = "quickstart"
version = "0.1.0"
description = "A quickstart for the OLAS AI agents"
authors = ["David Vilela <dvilelaf@gmail.com>", "Viraj Patel <vptl185@gmail.com>", "Ojuswi Rastogi <ojuswimail@gmail.com>"]
readme = "README.md"
package-mode = false
packages = []
include = []

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
olas-operate-middleware = { git = "https://github.com/valory-xyz/olas-operate-middleware.git", rev = "8c51c2a76d282109f6d3e8bd0de14f696e4bc803" }
tqdm = "^4.67.1"

[tool.poetry.group.dev.dependencies]
pexpect = "^4.9.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
